# config-server/src/main/resources/application.yml
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorzuo/springcloud-jwt-demo-config  # 你的 Git 仓库
          search-paths: config-repo